### ISSUE TITLE
Fix the `sha256` value when creating the lfs items.

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-gitdatahub#12]
We need to define how are we going to receive this value in the `package_dict` and update the `after_update` method accordly.

**Comment by uwaheed88** [comment]
@pdelboca Another addition, maybe we can add a `sha256_updated` boolean flag which will represent whether the sha256 is updated for the resource that has been uploaded.

**Comment by pdelboca** [comment]
Closing this since both values are keys in the resource dictionary: `sha256` and `size` just like we implemented it.
